### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by schnoepf** [telota/existance#5]
existance upgrade --id 8006 --version 4.5.1
Obtaining latest available version. ✔
Please report this unhandled exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/existance/__init__.py", line 64, in execute_plan
    action.do()
  File "/usr/local/lib/python3.7/dist-packages/existance/actions.py", line 388, in do
    dialect='instances_settings'
  File "/usr/local/lib/python3.7/dist-packages/existance/actions.py", line 386, in <dictcomp>
    for x in csv.DictReader(
ValueError: invalid literal for int() with base 10: '#8005'
Rolling back changes…

**Comment by schnoepf** [comment]
I think I got it. In the csv there is an outcommented line.
