### ISSUE TITLE
unhandled exception #2

### ISSUE THREAD

**Issue by schnoepf** [telota/existance#6]
Error: Invalid or corrupt jarfile /var/cache/existance/exist-installer-4.5.1.jar
Restoring old configs. ✖️
Please report this unhandled exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/existance/__init__.py", line 64, in execute_plan
    action.do()
  File "/usr/local/lib/python3.7/dist-packages/existance/actions.py", line 428, in do
    with config.open('tw') as f:
  File "/usr/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/exist_ediarum_avh_8006/existdb/conf.xml'
Rolling back changes… 
Removing installation folder. ✔
Removing data dir. ✔
Restoring installation and data snapshot. ✖️
Please report this unhandled exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/existance/__init__.py", line 64, in execute_plan
    action.do()
  File "/usr/local/lib/python3.7/dist-packages/existance/actions.py", line 428, in do
    with config.open('tw') as f:
  File "/usr/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/exist_ediarum_avh_8006/existdb/conf.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/existance/__init__.py", line 45, in do_rollback
    action.undo()
  File "/usr/local/lib/python3.7/dist-packages/existance/actions.py", line 376, in undo
    shutil.rmtree(data_dir)
  File "/usr/lib/python3.7/shutil.py", line 476, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 474, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/exist_ediarum_avh_8006/data'
The rollback is continued anyway.
Please report this unhandled exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/existance/__init__.py", line 64, in execute_plan
    action.do()
  File "/usr/local/lib/python3.7/dist-packages/existance/actions.py", line 428, in do
    with config.open('tw') as f:
  File "/usr/lib/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/exist_ediarum_avh_8006/existdb/conf.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/existance/__init__.py", line 45, in do_rollback
    action.undo()
  File "/usr/local/lib/python3.7/dist-packages/existance/actions.py", line 75, in undo
    raise RuntimeError('This code path is not expected yet.')
RuntimeError: This code path is not expected yet.
The rollback is continued anyway.

**Comment by schnoepf** [comment]
Assumption: exist-installer-4.5.1.jar is corrupted.

**Comment by schnoepf** [comment]
anyway, rollback didn't work. Issue closed

**Comment by funkyfuture** [comment]
there is not 4.5.1 release and such faulty user input should be intercepted.
